### ISSUE TITLE
repo transfer

### ISSUE THREAD

**Issue by chiaweh2** [chiaweh2/marine-heatwave-cookbook#11]
Hi @ProjectPythia/core, I just transfer the repo but it appears the GitHub page is not updated for some reason. And I am guessing since I am not the owner of the repo. I cannot edit the url showing on the right column of the page. Thanks! I had a great hacking at the Pythia cookoff 2023. And it is really nice to know you all in person!

**Comment by r-ford** [comment]
Hi @chiaweh2, I just made you admin on this repo, so you should have access to the settings now.

**Comment by chiaweh2** [comment]
@r-ford Thanks! I have made the changes after your help.
